### ISSUE TITLE
`events` endpoint rejects POST requests

### ISSUE THREAD

**Issue by jdemaeyer** [pirsch-analytics/pirsch-go-proxy#5]
Thanks a lot for supplying this Docker image, it was really easy to set up with the supplied docker-compose example!

My proxy returns `405 Method Not Allowed` for events sent by the extended JS snippet. I guess [this `router.Get()`](https://github.com/pirsch-analytics/pirsch-go-proxy/blob/master/handler.go#L35) should be `router.Post()`?

I also ran into "#pirschextendedjs tag not found" when using the example snippet for embedding the extended script that was [printed at startup](https://github.com/pirsch-analytics/pirsch-go-proxy/blob/master/cmd/main.go#L20-L45), and had to adjust the `id` of the `<script>` tag.

**Comment by Kugelschieber** [comment]
Hey Jakob,

Thanks for reporting! I've released an update that fixes both issues. Can you try version 2.0.1?

**Comment by jdemaeyer** [comment]
Yep that worked like a charm! thanks a lot :)
